[project]
name = "webapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.6",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
